if !isdirectory(expand("~/.vim/bundle/vundle/"))
  silent !echo "Installing Vundle..."
  silent !mkdir -p ~/.vim/bundle
  silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
endif

set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle "gmarik/vundle"

" Signify (vcs info)
Bundle 'mhinz/vim-signify'

" Easy motion to navigate with a few keystrokes
Bundle 'EasyMotion'

" Syntax check
Bundle 'Syntastic'

" Change surroundings
Bundle 'surround.vim'

" Navigate undo history
Bundle 'Gundo'

" unimpaired.vim : Pairs of handy bracket mappings
Bundle 'unimpaired.vim'

" Smarter status line
Bundle 'bling/vim-airline'

" Smart closing for brackets, quotes, parenthesis, etc
Bundle 'delimitMate.vim'

" Add tab completion inside "/" search
Bundle 'SearchComplete'

" Smart(er) search and replace
Bundle 'abolish.vim'

" CamelCase motions
Bundle 'camelcasemotion'

" Colorschemes
Bundle 'flazz/vim-colorschemes'

filetype plugin on
filetype indent on

" Color theme
set bg=dark
colorscheme oceanblack256

" Enable the fucking mouse selection
set mouse=a

"Boy, this trick saves lifes
nnoremap ; :

" Clean highlighted searches
nmap <silent> ,/ :nohlsearch<CR>

" Fast movement through splits
map <up> <c-w>k
map <down> <c-w>j
map <left> <c-w>h
map <right> <c-w>l

" Bubble single lines
nmap <C-Up> [e
nmap <C-Down> ]e
" Bubble multiple lines
vmap <C-Up> [egv
vmap <C-Down> ]egv

" Gundo config
nnoremap <F5> :GundoToggle<CR>

"Airline
let g:airline_powerline_fonts = 1

"" Disable MiniBufExplorer
let loaded_minibufexplorer = 1

let mapleader = ","
let g:mapleader = ","

" Number of undo levels
set undolevels=1000

" Text pasting madness
set pastetoggle=<F10>
inoremap <C-v> <F10><C-r>+<F10>

"Sy config
let g:signify_mapping_next_hunk = ']c'
let g:signify_mapping_prev_hunk = '[c'

" Disable Background Color Erase
set t_ut=

set history=500

set cursorline

" Set to auto read when a file is changed from the outside
set autoread

" Set 7 lines to the cursor - when moving vertically using j/k
set so=7

"Always show current position
set ruler

" Height of the command bar
set cmdheight=2

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch

" Don't redraw while executing macros (good performance config)
set lazyredraw

" For regular expressions turn magic on
set magic

" Show matching brackets when text indicator is over them
set showmatch

" How many tenths of a second to blink when matching brackets
set mat=2

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

set listchars=tab:▶·,trail:·
set list

" Show status line
set laststatus=2

" Enable syntax highlighting
syntax enable

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

set t_Co=256

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Turn backup off, since most stuff is in SVN, git et.c anyway...
set nobackup
set nowb
set noswapfile

" Use spaces instead of tabs
set expandtab

" Be smart when using tabs ;)
set smarttab

" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=4

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

set hidden

set wildmenu
"set wildmode=list:longest

set number

highlight clear SignColumn

set clipboard=unnamedplus
