export GOPATH=$HOME/go

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/qt/bin:/opt/android-sdk/platform-tools/:/opt/android-sdk/tools/:/opt/phabricator/arcanist/bin:~/bin:~/.cargo/bin:$GOPATH/bin:$HOME/.rbenv/shims


NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$PATH:$NPM_PACKAGES/bin"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
