export GOPATH=$HOME/go

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/qt/bin:/opt/android-sdk/platform-tools/:/opt/android-sdk/tools/:/opt/phabricator/arcanist/bin:~/bin:~/.cargo/bin:$GOPATH/bin:$HOME/.rbenv/shims

NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$PATH:$NPM_PACKAGES/bin"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
source "$HOME/.cargo/env"
. "$HOME/.cargo/env"

export TIMEWARRIORDB=$HOME/Nextcloud/TimeW/.timewarrior
export TASKRC=$HOME/Nextcloud/Task/.taskrc
export TASKDATA=$HOME/Nextcloud/Task/.task
