export GOPATH=$HOME/go

export PATH=$(realpath ~/.cargo/bin):$(realpath ~/bin):$GOPATH/bin:$HOME/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin/vendor_perl:/usr/bin/core_perl

export NPM_CONFIG_PREFIX=$HOME/.local/
export PATH="$NPM_CONFIG_PREFIX/bin:$PATH"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
