# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [ -f "$HOME/.zplug/init.zsh" ]; then source $HOME/.zplug/init.zsh; fi
if [ -f '/usr/share/zplug/init.zsh' ]; then source /usr/share/zplug/init.zsh; fi
if [ -f '/usr/share/zsh/scripts/zplug/init.zsh' ]; then source /usr/share/zsh/scripts/zplug/init.zsh; fi

zplug "willghatch/zsh-saneopt"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-completions"
zplug "junegunn/fzf", use:"shell/*.zsh"
zplug "cal2195/q"
zplug "mafredri/zsh-async"
zplug "djui/alias-tips"
zplug "voronkovich/gitignore.plugin.zsh"
zplug "aubreypwd/zsh-plugin-download"
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/ssh-agent", from:oh-my-zsh
zplug "jeffreytse/zsh-vi-mode"
zplug "joshskidmore/zsh-fzf-history-search"
zplug "romkatv/powerlevel10k", as:theme, depth:1

zplug load

export HISTFILE=~/.zsh_history
export HISTSIZE=999999999
export SAVEHIST=$HISTSIZE

alias ls="ls --color=auto"
alias nv='nvim'
export EDITOR='nvim'

export PATH="$(realpath ~/.cargo/bin):$HOME/.local/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/rzanoni/tools/google-cloud-sdk/path.zsh.inc' ]; then . '/home/rzanoni/tools/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/rzanoni/tools/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/rzanoni/tools/google-cloud-sdk/completion.zsh.inc'; fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

fpath=(~/.zsh/completion $fpath)
