# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ys"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git svn archlinux screen)

source $ZSH/oh-my-zsh.sh

# TODO, use separate cfg files for home and work pcs
#source /usr/share/fzf/completion.zsh
#source /usr/share/fzf/key-bindings.zsh

bindkey '\ex' fzf-cd-widget


export EDITOR='vim'

alias ec='emacsclient -t -a "" -c'
alias et='emacs -nw'
alias ek='emacs -nw --eval "(kill-emacs)"'
alias t='tig'
alias to='todo'
alias v='vim --servername VIM --remote-silent '
alias vt='vim --servername VIM --remote-silent-tab '
alias dbopatch="arc diff --reviewers rodrigo.golive HEAD~1"
alias apclear="git branch -a | grep arcpatch | xargs git branch -D"
alias startx='ssh-agent startx'

# TODO, use separate cfg files for home and work pcs
#eval "$(rbenv init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
