source /usr/share/zsh/scripts/zplug/init.zsh

export ZOXIDE_CMD_OVERRIDE=cd

zplug "willghatch/zsh-saneopt"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "junegunn/fzf", use:"shell/*.zsh"
zplug "zsh-users/zsh-history-substring-search", defer:3
zplug "marlonrichert/zsh-autocomplete"
zplug "jeffreytse/zsh-vi-mode"
zplug "MichaelAquilina/zsh-auto-notify"
zplug "cal2195/q"
zplug "mafredri/zsh-async"
zplug "djui/alias-tips"
zplug "voronkovich/gitignore.plugin.zsh"
zplug "aubreypwd/zsh-plugin-download"
zplug "amyreese/zsh-take"
zplug "MohamedElashri/exa-zsh"
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/ssh-agent", from:oh-my-zsh
zplug "plugins/zoxide", from:oh-my-zsh
zplug "themes/alanpeabody", from:oh-my-zsh

zplug load

export HISTFILE=~/.zsh_history
export HISTSIZE=999999999
export SAVEHIST=$HISTSIZE

alias nv='nvim'
export EDITOR='nvim'

export GEM_HOME="$HOME/gems"
export GEM_PATH="$HOME/gems"
export PATH="$HOME/gems/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"

export PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/zanoni/projects/google/google-cloud-sdk/path.zsh.inc' ]; then . '/home/zanoni/projects/google/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/zanoni/projects/google/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/zanoni/projects/google/google-cloud-sdk/completion.zsh.inc'; fi
